### ISSUE TITLE
XACT fails to craft

### ISSUE THREAD

**Issue by target-san** [Xhamolk/XACT#73] opened 2013-05-04 08:43 UTC
Sometimes I observe following issue:
1. Set recipe from NEI
2. Try to craft device
Observed: crafted item disappears after several seconds, with resources returning back to XACT's inventory. Might happen even after exiting XACT GUI.
Observed: very often; several times observed when setting recipe manually; didn't happen on vanilla items
Items: Thermal Expansion complex machines
XACT version: 0.3.1

**Comment by Xhamolk** [comment] 2013-05-07 07:38
Please try the latest version. The crafting mechanism has been significantly changed since 0.3.1.

**Comment by Xhamolk** [comment] 2013-05-09 05:22
Closing this as I can't reproduce.

**Closed as completed by Xhamolk** 2013-05-09 05:22 UTC
